[1m============================= test session starts ==============================[0m
platform linux -- Python 3.12.3, pytest-8.4.1, pluggy-1.6.0 -- /mnt/c/devops-work/gcp-python-api/venv/bin/python3
cachedir: .pytest_cache
rootdir: /mnt/c/devops-work/gcp-python-api
configfile: pytest.ini
testpaths: tests
plugins: anyio-4.9.0
[1mcollecting ... [0mcollected 2 items

tests/test_main.py::test_read_root [32mPASSED[0m[33m                                [ 50%][0m
tests/test_main.py::test_health_check [32mPASSED[0m[33m                             [100%][0m

[33m=============================== warnings summary ===============================[0m
venv/lib/python3.12/site-packages/_pytest/config/__init__.py:1474
  /mnt/c/devops-work/gcp-python-api/venv/lib/python3.12/site-packages/_pytest/config/__init__.py:1474: PytestConfigWarning: Unknown config option: python_paths
  
    self._warn_or_fail_if_strict(f"Unknown config option: {key}\n")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
------ generated xml file: /mnt/c/devops-work/gcp-python-api/results.xml -------
[33m========================= [32m2 passed[0m, [33m[1m1 warning[0m[33m in 2.26s[0m[33m =========================[0m
